# frozen_string_literal: true

plugins:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'lib/snaker.rb'
    - 'lib/snaker-sources.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '**/*.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Minitest/MultipleAssertions:
  Max: 10

Gemspec/RequiredRubyVersion:
  Enabled: false
